### ISSUE TITLE
Use desctructuring

### ISSUE THREAD

**Issue by brion25** [FabianFavila/github-finder-react#2]
please ¡use destructuring to make it easier to read

https://github.com/FabianFavila/github-finder-react/blob/50e122ec00377d5fcaf41a0adcc8a310df56d453/src/components/Detail.js#L79-L87

**Comment by FabianSolano** [comment]
Hello, brion25!

This issue has been covered with commit [8b3e59b48ae37d43a585d63cbf4e7fb89a5e8e29](https://github.com/FabianFavila/github-finder-react/commit/8b3e59b48ae37d43a585d63cbf4e7fb89a5e8e29).

I'll proceed to close this issue; if you consider it wasn't resolved please let me know so I can reopen it and work on it :)
